[package]
name = "Torch Hotkey Expanded"
description = "This mod adds a hotkey to ready a light source."
homepage = "https://www.nexusmods.com/morrowind/mods/57474"
repository = "https://github.com/C3pa/Morrowind-Torch-Hotkey-Expanded"
authors = [ "C3pa" ]
version = "1.0.1"

[dependencies.mwse]
buildnumber = 4594

[dependencies.mge-xe]
version = ">=0.18.0"

[tools.mwse]
lua-mod = "Torch Hotkey Expanded"
